"""Run the real processor on the demo files and write the snapshot the static frontend consumes.

    python -m processor.generate_snapshot

The output is deterministic (no timestamps), so it can be checked in and diffed.
"""
import json
from pathlib import Path

from .cli import ROOT, load_defaults
from .pipeline import process_file

DEMO = ROOT / "demo"
OUT = ROOT / "frontend" / "src" / "data" / "snapshot.json"
EXAMPLE_FILE = "DEMO_CB77.xml"
EXAMPLE_CODE = "EBA_FIN_X01"
SHOWCASE_KEYS = [("FIN", "X01"), ("FIN", "X02"), ("RISK", "B01")]  # the three rows shown in the Excel section


def build_snapshot() -> dict:
    mapper, registry = load_defaults()
    results = {name: process_file(DEMO / name, mapper, registry) for name in ("DEMO_CB77.xml", "DEMO_MB0100.xml")}

    files = {}
    for name, r in results.items():
        files[r.meta["formulier_id"]] = {
            "file": name,
            "summary": r.stats,
            "issues": [i.to_dict() for i in r.issues],
            "output": r.lines,
            "records": r.records,
            "groups": r.groups,
        }

    cb77 = results[EXAMPLE_FILE]
    record = next(x for x in cb77.records if x["source"]["value"] == EXAMPLE_CODE)
    mapping = next(s for s in record["steps"] if s["stage"] == "excel_mapping")
    src = record["source"]
    example = {
        "file": EXAMPLE_FILE,
        "source_line": src["line"],
        "stages": {
            "xml_input": '<post value="{value}" rij="{rij}" kolom="{kolom}" rijnr="{rijnr}"/>'.format(**src),
            "excel_mapping": {k: mapping[k] for k in ("domain", "member", "structure", "date")},
            "business_rule": "{code} → {d} + {m} → hierarchy lookup → {s}".format(
                code=EXAMPLE_CODE, d=mapping["domain"], m=mapping["member"], s=mapping["structure"]),
            "jsonl_output": _without_report_code(record["output"]),
        },
    }

    excel_rows = []
    for domain, member in SHOWCASE_KEYS:
        entry = mapper.lookup(domain, member)
        excel_rows.append({"domain": entry.domain, "member": entry.member, "structure": entry.structure})

    grid = {}
    for line in cb77.lines:
        cell = json.loads(line)
        grid.setdefault(cell["axis_row"], {})[cell["axis_col"]] = cell["Value"]

    return {
        "notice": "Generated by processor/generate_snapshot.py from fictional demo data. Do not edit by hand.",
        "files": files,
        "example": example,
        "excel_rows": excel_rows,
        "generic_rules": registry.generic_rules,
        "duplicate_example": next(i.to_dict() for i in cb77.issues if i.type == "duplicate"),
        "mapping_miss_example": next(i.to_dict() for i in cb77.issues if i.type == "mapping-miss"),
        "report_grid": grid,
    }


def _without_report_code(line: str) -> str:
    """The page copy shows the simple three-field record; report_code is a labelled extra in the data files."""
    data = json.loads(line)
    data.pop("report_code", None)
    return json.dumps(data, separators=(",", ":"), ensure_ascii=False)


def main() -> None:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(build_snapshot(), indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print("wrote {}".format(OUT.relative_to(ROOT)))


if __name__ == "__main__":
    main()
